[package]
name = "jito-points"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-sdk = { version = "1.16" }
solana-client = { version = "1.16" }
tokio = "1"
log = "0.4"